_base_: default.yaml

data:
  dir: ~/Datasets/Geolife Trajectories 1.3
  max_test_trajs: 500

model:
  type: transformer
  hidden_dim: 128
  n_heads: 4
  n_layers: 3
  dropout: 0.1
  n_components: 3

simulation:
  strategies: threshold

output:
  note: geolife_transformer_threshold
